spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS MY_SCHEMA\;
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create-drop
  h2.console.enabled: true