spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS wordle\;SET SCHEMA wordle\;
  jpa:
    hibernate.ddl-auto: validate
  sql.init.data-locations: classpath:data.sql,classpath:data-dev-users.sql
  h2.console.enabled: true

app:
  frontend:
    success-redirect: "http://localhost:3001/"
  security:
    refresh:
      cookie-name: wd_refresh
      cookie-secure: false
  websocket:
    allowed-origins:
      - "http://localhost:${server.port}"
      - "http://localhost:3001"

room:
  cleanup:
    cron: "-"

refresh-token:
  cleanup:
    cron: "-"
