spring:
  datasource:
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:${DB_PORT}/postgres?prepareThreshold=0&currentSchema=wordle
    username: ${DB_USER}
    password: ${DB_PASSWORD}

app:
  frontend:
    success-redirect: "https://dariolab.com/wordle-duel/"
  websocket:
    allowed-origins:
      - "https://dariolab.com"
