name: Coverage

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write   # allow workflow to comment on the PR

jobs:
  coverage:
    uses: dario-mr/ci-pipelines/.github/workflows/java-coverage.yml@feature/coverage-diff
    with:
      pull-request-number: ${{ github.event.pull_request.number }}
      ci-pipelines-ref: 'feature/coverage-diff'
